export const ADD_FUNCTIONAL_ADMIN = "ADD_FUNCTIONAL_ADMIN";
export const ADD_FUNCTIONAL_ADMIN_SUCCESS = "ADD_FUNCTIONAL_ADMIN_SUCCESS";
export const EDIT_FUNCTIONAL_AMDIN = "EDIT_FUNCTIONAL_ADMIN";
export const EDIT_FUNCTIONAL_ADMIN_SUCCESS = "EDIT_FUNCTIONAL_ADMIN_SUCCESS";
export const DELETE_FUNCTIONAL_ADMIN_SUCCESS =
  "DELETE_FUNCTIONAL_ADMIN_SUCCESS";
export const DELETE_FUNCTIONAL_ADMIN = "DELETE_FUNCTIONAL_ADMIN";
export const GET_FUNCTIONAL_ADMIN_LIST = "GET_FUNCTIONAL_ADMIN_LIST";
export const GET_FUNCTIONAL_FULL_ADMIN_LIST = "GET_FUNCTIONAL_FULL_ADMIN_LIST"
export const GET_FUNCTIONAL_FULL_ADMIN_LIST_SUCCESS="GET_FUNCTIONAL_FULL_ADMIN_LIST_SUCCESS"
export const GET_FUNCTIONAL_ADMIN_LIST_SUCCESS ="GET_FUNCTIONAL_ADMIN_LIST_SUCCESS";

export const TOGGLE_ADMIN = "TOGGLE_ADMIN";

export const ADD_ADMIN_STATUS = "ADD_ADMIN_STATUS";

export const CHANGE_LOADING_STATE = "CHANGE_LOADING_STATE";

export const DELETE_ADMIN = "DELETE_ADMIN";

export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";