export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const GET_GATEGORIES = "GET_GATEGORIES";
export const GET_GATEGORIES_SUCCESS = "GET_GATEGORIES_SUCCESS";
export const TOGGLE_STATUS = "TOGGLE_STATUS";
export const EDIT_TYPE = "EDIT_TYPE";
export const EDIT_TYPE_SUCCESS = "EDIT_TYPE_SUCCESS";
export const DELETE_TYPE = "DELETE_TYPE";
export const DELETE_TYPE_SUCCESS = "DELETE_TYPE_SUCCESS";





