export const BANKS_LIST_LOADING =
  "corporates/BANKS_LIST_LOADING";
export const BANKS_LIST_SUCCESS =
  "corporates/BANKS_LIST_SUCCESS";
export const BANKS_RESET = "corporates/BANKS_LIST_RESET";
export const BANKS_API_ERROR = "corporates/API_ERROR";
export const RETRIEVE_BANK = "corporates/RETRIEVE_BANK";
export const RETRIEVE_BANK_SUCCESS =
  "corporates/RETRIEVE_BANK_SUCCESS";
export const ADD_BANK_INFORMATION = "ADD_BANK_INFORMATION";
export const ADD_BANK_INFORMATION_SUCCESS =
  "ADD_BANK_INFORMATION_SUCCESS";
export const ADD_BANK_GEOGRAPHY = "ADD_BANK_GEOGRAPHY";
export const ADD_BANK_GEOGRAPHY_SUCCESS =
  "ADD_BANK_GEOGRAPHY_SUCCESS";
export const ADD_NEW_CORPORATE_ADMIN = "ADD_CORPORATE_ADMIN";
export const ADD_NEW_CORPORATE_ADMIN_SUCCESS =
  "ADD_CORPORATE_ADMIN_SUCCESS";
export const SFTP_CONNECTION = "SFTP_CONNECTION";
export const SFTP_CONNECTION_SUCCESS = "SFTP_CONNECTION_SUCCESS";

export const ENABLE_EDIT_MODE = "ENABLE_EDIT_MODE";
export const DISABLE_EDIT_MODE = "DISABLE_EDIT_MODE";
export const NEXT_STEP = "NEXT_STEP";


export const EDIT_BANK_INFORMATION = "EDIT_BANK_INFORMATION";
export const EDIT_BANK_INFORMATION_SUCCESS =
  "EDIT_BANK_INFORMATION_SUCCESS";
export const EDIT_BANK_GEOGRAPHY = "EDIT_BANK_GEOGRAPHY";
export const EDIT_BANK_GEOGRAPHY_SUCCESS =
  "EDIT_BANK_GEOGRAPHY_SUCCESS";
export const TOGGLE_BANK = "TOGGLE_BANK";
export const TOGGLE_BANK_SUCCESS = "TOGGLE_BANK_SUCCESS";

export const DELETE_CORPORATE = "DELETE_CORPORATE";
export const DELETE_CORPORATE_SUCCESS = "DELETE_CORPORATE_SUCCESS";